GET https://python-project-hangman-46b9.onrender.com/highscores

###

GET https://python-project-hangman-46b9.onrender.com/highscores/1

###

GET https://python-project-hangman-46b9.onrender.com/highscores?sort=desc

###

GET https://python-project-hangman-46b9.onrender.com/highscores?sort=asc&limit=10

###

GET https://python-project-hangman-46b9.onrender.com/highscores?sort=desc&limit=10 

###

DELETE https://python-project-hangman-46b9.onrender.com/highscores/8

###

