GET https://python-project-hangman-46b9.onrender.com?password=hirttoukko

###

GET https://python-project-hangman-46b9.onrender.com/3?password=hirttoukko

###

GET https://python-project-hangman-46b9.onrender.com?sort=desc&password=hirttoukko

###

GET https://python-project-hangman-46b9.onrender.com?sort=asc&limit=3&password=hirttoukko

###

DELETE https://python-project-hangman-46b9.onrender.com/highscores/1?password=hirttoukko

###

POST https://python-project-hangman-46b9.onrender.com/highscores?password=hirttoukko
content-type: application/json

{ "name": "Joonas", "time": "00:40" }